coverage:
  status:
    project:
      default:
        target: auto # Automatically set the target coverage
        threshold: 1% # Allow coverage to decrease by up to 1% without failing
        informational: true # Don't fail the build if coverage is below the threshold
        only_pulls: true # Only show coverage changes on pull requests
