import polars as pl

from claion.data.utils import get_root_path


def display_adults():
    """
    Display the contents of the adult dataset parquet files generated by extract_and_save_adults.
    """
    # Load dataset path
    root_path = get_root_path()
    dataset_path = root_path / "data" / "speechocean762"

    # List of parquet files to display
    parquet_files = list(dataset_path.glob("*_adults.parquet"))

    if not parquet_files:
        print("No adult dataset files found.")
        return

    for file_path in parquet_files:
        print(f"Displaying contents of {file_path}:")
        df = pl.read_parquet(file_path)
        print(df)
        print("-" * 50)


if __name__ == "__main__":
    display_adults()
